# Generated by Django 4.1.1 on 2022-09-18 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 19, 20, 27, 240879, tzinfo=datetime.timezone.utc)),
        ),
    ]
