# Generated by Django 4.1.1 on 2022-09-18 20:57

import app.models_validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_id_topic_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 20, 57, 2, 619477, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_uuid',
            field=models.TextField(validators=[app.models_validators.TopicValidators.validate_uuid]),
        ),
    ]
