# Generated by Django 4.1.1 on 2022-09-19 21:29

import app.models_validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_topic_description_topic_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 21, 29, 58, 871861, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_uuid',
            field=models.TextField(default='b394ee4cf6e34ad4a05dfc5f3fdb476c', validators=[app.models_validators.TopicValidators.validate_uuid]),
        ),
    ]
