# Generated by Django 4.1.1 on 2022-09-20 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customuser_date_joined_alter_topic_topic_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 18, 20, 14, 438362, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_uuid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
