class ServiceException(Exception):
    ...

class GetTopicServiceException(ServiceException):
    ...


class UserNotFoundException(ServiceException):
    ...


class CreateInputMessageException(ServiceException):
   ...